modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="flavio_y_papi"
version="1.0.0"
displayName="Flavio y Papi"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="USER, MCreator"

[[dependencies.flavio_y_papi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



